# Generated by Django 3.1 on 2021-03-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringexam',
            name='minimum_percentage',
            field=models.CharField(default='should have passed 12th board exams', max_length=50),
            preserve_default=False,
        ),
    ]
