# Generated by Django 3.1 on 2021-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_engineeringexam_minimum_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringexam',
            name='purpose',
            field=models.TextField(max_length=150),
        ),
    ]
