# Generated by Django 3.1 on 2021-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210306_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringexam',
            name='eligibility',
            field=models.TextField(max_length=100),
        ),
    ]
