# Generated by Django 3.1 on 2021-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210306_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefNavArm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField(max_length=150)),
                ('eligibility', models.TextField(max_length=250)),
                ('application_mode', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=150)),
                ('minimum_percentage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField(max_length=150)),
                ('eligibility', models.TextField(max_length=250)),
                ('application_mode', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=150)),
                ('minimum_percentage', models.CharField(max_length=50)),
            ],
        ),
    ]
