# Generated by Django 3.1 on 2021-03-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_allexams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllExams',
            new_name='AllExam',
        ),
    ]
